# version: 2 # CircleCI version
# https://medium.com/@einenlum/testing-your-app-with-docker-compose-on-circleci-ffd4cc8e2cfa
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            docker-compose -v &&
            docker-compose up -d

      # Database setup
      - run: docker-compose run app bundle exec rake db:create
      - run: docker-compose run app bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            docker-compose run app bundle exec rake test
