---
version: 2
jobs:
  build:
    machine: true  # Use a Linux VM instead of docker environment
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            docker-compose -v &&
            docker-compose up -d
      - run:
          name: create database
          command: docker-compose run app bundle exec rake db:create
      - run:
          name: load database schema
          command: docker-compose run app bundle exec rake db:schema:load
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"
            docker-compose run app bundle exec rspec
